[2023-11-21T09:51:53.205+0300] {processor.py:156} INFO - Started process (PID=23883) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:51:53.206+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T09:51:53.207+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:51:53.207+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:51:53.218+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:51:53.218+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T09:51:53.219+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:51:53.218+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T09:51:53.219+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:51:53.224+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2023-11-21T09:52:29.901+0300] {processor.py:156} INFO - Started process (PID=24317) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:52:29.902+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T09:52:29.903+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:52:29.903+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:52:29.920+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:52:29.920+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T09:52:29.920+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:52:29.920+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T09:52:29.921+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:52:29.928+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-11-21T09:53:07.837+0300] {processor.py:156} INFO - Started process (PID=24597) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:53:07.838+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T09:53:07.838+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:53:07.838+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:53:07.848+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:53:07.848+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T09:53:07.848+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:53:07.848+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T09:53:07.849+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:53:07.854+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-11-21T09:53:46.863+0300] {processor.py:156} INFO - Started process (PID=24848) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:53:46.866+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T09:53:46.867+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:53:46.867+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:53:46.885+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:53:46.885+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T09:53:46.885+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:53:46.885+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T09:53:46.886+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:53:46.893+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-11-21T09:54:22.236+0300] {processor.py:156} INFO - Started process (PID=25059) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:54:22.239+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T09:54:22.240+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:54:22.240+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:54:22.262+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:54:22.262+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T09:54:22.262+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:54:22.262+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T09:54:22.263+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:54:22.269+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-11-21T09:54:59.582+0300] {processor.py:156} INFO - Started process (PID=25299) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:54:59.586+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T09:54:59.587+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:54:59.587+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:54:59.604+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:54:59.603+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T09:54:59.604+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:54:59.604+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T09:54:59.604+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:54:59.612+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-11-21T09:55:37.183+0300] {processor.py:156} INFO - Started process (PID=25612) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:55:37.187+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T09:55:37.188+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:55:37.188+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:55:37.213+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:55:37.212+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T09:55:37.213+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:55:37.213+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T09:55:37.213+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:55:37.220+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2023-11-21T09:56:14.483+0300] {processor.py:156} INFO - Started process (PID=25842) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:56:14.487+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T09:56:14.488+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:56:14.487+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:56:14.504+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:56:14.503+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T09:56:14.505+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:56:14.505+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T09:56:14.505+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:56:14.514+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-11-21T09:56:50.569+0300] {processor.py:156} INFO - Started process (PID=26106) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:56:50.571+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T09:56:50.571+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:56:50.571+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:56:50.585+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:56:50.585+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T09:56:50.586+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:56:50.586+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T09:56:50.586+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:56:50.593+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-11-21T09:57:28.862+0300] {processor.py:156} INFO - Started process (PID=26339) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:57:28.863+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T09:57:28.864+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:57:28.864+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:57:28.874+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:57:28.874+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T09:57:28.874+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:57:28.874+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T09:57:28.874+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:57:28.880+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2023-11-21T09:58:05.912+0300] {processor.py:156} INFO - Started process (PID=26582) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:58:05.913+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T09:58:05.914+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:58:05.914+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:58:05.928+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:58:05.928+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T09:58:05.929+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:58:05.928+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T09:58:05.929+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:58:05.936+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-11-21T09:58:42.659+0300] {processor.py:156} INFO - Started process (PID=27157) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:58:42.661+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T09:58:42.662+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:58:42.662+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:58:42.675+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:58:42.675+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T09:58:42.676+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:58:42.676+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T09:58:42.676+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:58:42.683+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2023-11-21T09:59:18.779+0300] {processor.py:156} INFO - Started process (PID=27414) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:59:18.779+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T09:59:18.780+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:59:18.780+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:59:18.790+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:59:18.790+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T09:59:18.790+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:59:18.790+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T09:59:18.790+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:59:18.796+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-11-21T09:59:54.911+0300] {processor.py:156} INFO - Started process (PID=27644) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:59:54.913+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T09:59:54.915+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:59:54.915+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:59:54.945+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:59:54.945+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T09:59:54.945+0300] {logging_mixin.py:117} INFO - [2023-11-21T09:59:54.945+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T09:59:54.946+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T09:59:54.954+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2023-11-21T10:00:29.985+0300] {processor.py:156} INFO - Started process (PID=27854) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:00:29.986+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:00:29.986+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:00:29.986+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:00:29.996+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:00:29.995+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:00:29.996+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:00:29.996+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:00:29.996+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:00:30.002+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-11-21T10:01:06.420+0300] {processor.py:156} INFO - Started process (PID=28082) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:01:06.423+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:01:06.424+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:01:06.424+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:01:06.452+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:01:06.452+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:01:06.453+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:01:06.453+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:01:06.453+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:01:06.460+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2023-11-21T10:01:41.509+0300] {processor.py:156} INFO - Started process (PID=28359) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:01:41.510+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:01:41.510+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:01:41.510+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:01:41.520+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:01:41.520+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:01:41.520+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:01:41.520+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:01:41.521+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:01:41.526+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-11-21T10:02:17.727+0300] {processor.py:156} INFO - Started process (PID=28579) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:02:17.729+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:02:17.732+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:02:17.731+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:02:17.752+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:02:17.752+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:02:17.753+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:02:17.753+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:02:17.753+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:02:17.761+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2023-11-21T10:02:53.670+0300] {processor.py:156} INFO - Started process (PID=28813) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:02:53.673+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:02:53.675+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:02:53.675+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:02:53.707+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:02:53.706+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:02:53.707+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:02:53.707+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:02:53.707+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:02:53.715+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2023-11-21T10:05:22.738+0300] {processor.py:156} INFO - Started process (PID=30151) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:05:22.742+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:05:22.743+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:05:22.743+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:05:22.770+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:05:22.770+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:05:22.771+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:05:22.771+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:05:22.771+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:05:22.778+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2023-11-21T10:06:02.186+0300] {processor.py:156} INFO - Started process (PID=30527) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:06:02.188+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:06:02.189+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:06:02.188+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:06:02.207+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:06:02.206+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:06:02.207+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:06:02.207+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:06:02.208+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:06:02.219+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2023-11-21T10:06:39.749+0300] {processor.py:156} INFO - Started process (PID=30760) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:06:39.751+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:06:39.751+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:06:39.751+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:06:39.762+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:06:39.762+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:06:39.762+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:06:39.762+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:06:39.762+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:06:39.768+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2023-11-21T10:07:17.071+0300] {processor.py:156} INFO - Started process (PID=31017) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:07:17.075+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:07:17.076+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:07:17.076+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:07:17.096+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:07:17.095+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:07:17.096+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:07:17.096+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:07:17.096+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:07:17.103+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2023-11-21T10:07:55.477+0300] {processor.py:156} INFO - Started process (PID=31253) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:07:55.478+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:07:55.479+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:07:55.479+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:07:55.494+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:07:55.492+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:07:55.494+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:07:55.494+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:07:55.494+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:07:55.502+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-11-21T10:08:33.775+0300] {processor.py:156} INFO - Started process (PID=31512) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:08:33.777+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:08:33.777+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:08:33.777+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:08:33.789+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:08:33.789+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:08:33.790+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:08:33.789+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:08:33.790+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:08:33.796+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2023-11-21T10:09:11.289+0300] {processor.py:156} INFO - Started process (PID=31756) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:09:11.291+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:09:11.291+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:09:11.291+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:09:11.307+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:09:11.306+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:09:11.307+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:09:11.307+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:09:11.307+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:09:11.315+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-11-21T10:09:54.943+0300] {processor.py:156} INFO - Started process (PID=32411) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:09:54.947+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:09:54.948+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:09:54.948+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:09:54.969+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:09:54.968+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:09:54.969+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:09:54.969+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:09:54.970+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:09:54.978+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-11-21T10:10:45.741+0300] {processor.py:156} INFO - Started process (PID=33184) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:10:45.742+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:10:45.742+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:10:45.742+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:10:45.752+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:10:45.752+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:10:45.752+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:10:45.752+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:10:45.753+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:10:45.758+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-11-21T10:11:23.391+0300] {processor.py:156} INFO - Started process (PID=33435) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:11:23.394+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:11:23.396+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:11:23.396+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:11:23.422+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:11:23.422+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:11:23.423+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:11:23.423+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:11:23.423+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:11:23.430+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2023-11-21T10:12:01.443+0300] {processor.py:156} INFO - Started process (PID=33685) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:12:01.445+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:12:01.446+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:12:01.445+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:12:01.463+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:12:01.462+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:12:01.463+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:12:01.463+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:12:01.464+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:12:01.474+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2023-11-21T10:12:39.945+0300] {processor.py:156} INFO - Started process (PID=33912) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:12:39.947+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:12:39.948+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:12:39.948+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:12:39.968+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:12:39.967+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:12:39.968+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:12:39.968+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:12:39.968+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:12:39.977+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2023-11-21T10:13:17.671+0300] {processor.py:156} INFO - Started process (PID=34163) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:13:17.673+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:13:17.675+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:13:17.674+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:13:17.699+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:13:17.698+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:13:17.699+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:13:17.699+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:13:17.699+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:13:17.708+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2023-11-21T10:14:09.542+0300] {processor.py:156} INFO - Started process (PID=34895) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:14:09.544+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:14:09.545+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:14:09.545+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:14:09.569+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:14:09.569+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:14:09.570+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:14:09.570+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:14:09.570+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:14:09.578+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2023-11-21T10:14:48.231+0300] {processor.py:156} INFO - Started process (PID=35322) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:14:48.233+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:14:48.233+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:14:48.233+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:14:48.244+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:14:48.244+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:14:48.244+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:14:48.244+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:14:48.244+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:14:48.250+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2023-11-21T10:15:25.990+0300] {processor.py:156} INFO - Started process (PID=35633) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:15:25.992+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:15:25.992+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:15:25.992+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:15:26.006+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:15:26.006+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:15:26.006+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:15:26.006+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:15:26.007+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:15:26.014+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2023-11-21T10:16:02.458+0300] {processor.py:156} INFO - Started process (PID=35859) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:16:02.460+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:16:02.460+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:16:02.460+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:16:02.477+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:16:02.476+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:16:02.477+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:16:02.477+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:16:02.477+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:16:02.485+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2023-11-21T10:16:40.111+0300] {processor.py:156} INFO - Started process (PID=36094) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:16:40.114+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:16:40.115+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:16:40.115+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:16:40.148+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:16:40.147+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:16:40.149+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:16:40.148+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:16:40.149+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:16:40.157+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2023-11-21T10:17:18.669+0300] {processor.py:156} INFO - Started process (PID=36379) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:17:18.672+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:17:18.674+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:17:18.673+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:17:18.700+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:17:18.699+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:17:18.700+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:17:18.700+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:17:18.700+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:17:18.709+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2023-11-21T10:17:55.491+0300] {processor.py:156} INFO - Started process (PID=36636) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:17:55.492+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:17:55.492+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:17:55.492+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:17:55.503+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:17:55.502+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:17:55.503+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:17:55.503+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:17:55.503+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:17:55.509+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-11-21T10:18:33.554+0300] {processor.py:156} INFO - Started process (PID=36898) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:18:33.556+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:18:33.557+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:18:33.557+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:18:33.573+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:18:33.572+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:18:33.573+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:18:33.573+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:18:33.573+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:18:33.581+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2023-11-21T10:19:12.575+0300] {processor.py:156} INFO - Started process (PID=37142) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:19:12.576+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:19:12.576+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:19:12.576+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:19:12.586+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:19:12.586+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:19:12.586+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:19:12.586+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:19:12.587+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:19:12.592+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2023-11-21T10:19:52.166+0300] {processor.py:156} INFO - Started process (PID=37451) to work on /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:19:52.169+0300] {processor.py:758} INFO - Processing file /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-11-21T10:19:52.172+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:19:52.171+0300] {dagbag.py:525} INFO - Filling up the DagBag from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:19:52.196+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:19:52.196+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-11-21T10:19:52.196+0300] {logging_mixin.py:117} INFO - [2023-11-21T10:19:52.196+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-11-21T10:19:52.197+0300] {processor.py:770} WARNING - No viable dags retrieved from /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-11-21T10:19:52.203+0300] {processor.py:178} INFO - Processing /home/user/Masaüstü/kafka/.env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
